### Site metadata ###

site_name: MkDocs Quickstart
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://fdecharlet.github.io/hello-world/

repo_url: https://github.com/fdecharlet/hello-world
edit_uri: edit/master/docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md

